=== 018gagvg/main/packages/e2e-tests/test-recipe-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Sentry JavaScript E2E Test Recipe",
  "type": "object",
  "properties": {
    "testApplicationName": {
      "type": "string",
      "description": "Name displayed in test output"
    },
    "buildCommand": {
      "type": "string",
      "description": "Command that is run to install dependencies and build the test application. This command is only run once before all tests. Working directory of the command is the root of the test application."
    },
    "buildTimeoutSeconds": {
      "type": "number",
      "description": "Timeout for the build command in seconds. Default: 60"
    },
    "tests": {
      "type": "array",
      "description": "Tests to run in this test application",
      "items": {
        "type": "object",
        "properties": {
          "testName": {
            "type": "string",
            "description": "Name displayed in test output"
          },
          "testCommand": {
            "type": "string",
            "description": "Command that is run to start the test. Working directory of the command is the root of the test application. If this command returns a non-zero exit code the test counts as failed."
          },
          "timeoutSeconds": {
            "type": "number",
            "description": "Test timeout in seconds. Default: 60"
          }
        },
        "required": ["testName", "testCommand"]
      }
    },
    "versions": {
      "type": "array",
      "description": "List of different dependency versions to test. If this property is provided, the tests will run for each item, if it is omitted, the tests will only run once with the dependencies provided in package.json.",
      "items": {
        "type": "object",
        "properties": {
          "dependencyOverrides": {
            "type": "object",
            "description": "Object to merge with the \"dependencies\" object in package.json.",
            "additionalProperties": { "type": "string" }
          }
        }
      }
    },
    "canaryVersions": {
      "type": "array",
      "description": "List of different dependency versions to test as part of the canary test. Canary tests are only run if the CANARY_E2E_TEST environment variable is set. If If CANARY_E2E_TEST is set and this property is provided, the tests will run for each item, if it is omitted, no tests will be executed.",
      "items": {
        "type": "object",
        "properties": {
          "dependencyOverrides": {
            "type": "object",
            "description": "Object to merge with the \"dependencies\" object in package.json.",
            "additionalProperties": { "type": "string" }
          }
        }
      }
    }
  },
  "required": ["testApplicationName", "tests"]
}

=== 018gagvg/main/packages/e2e-tests/test-applications/react-create-hash-router/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "react-create-hash-router",
  "buildCommand": "pnpm install && npx playwright install && pnpm build",
  "tests": [
    {
      "testName": "Playwright tests",
      "testCommand": "pnpm test"
    }
  ],
  "canaryVersions": [
    {
      "dependencyOverrides": {
        "react": "latest",
        "react-dom": "latest"
      }
    }
  ]
}

=== 018gagvg/main/packages/e2e-tests/test-applications/nextjs-13-app-dir/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "nextjs-13-app-dir",
  "buildCommand": "yarn install --pure-lockfile && npx playwright install && yarn build",
  "tests": [
    {
      "testName": "Production Build",
      "testCommand": "yarn test:prod"
    },
    {
      "testName": "Development Build",
      "testCommand": "yarn test:dev"
    }
  ],
  "canaryVersions": [
    {
      "dependencyOverrides": {
        "next": "latest"
      }
    }
  ]
}

=== 018gagvg/main/packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "standard-frontend-react-tracing-import",
  "buildCommand": "yarn install --pure-lockfile && npx playwright install && yarn build",
  "tests": [
    {
      "testName": "Playwright tests",
      "testCommand": "yarn test"
    }
  ],
  "canaryVersions": []
}

=== 018gagvg/main/packages/e2e-tests/test-applications/standard-frontend-next-app-dir/test-recipe.json
{
  "$schema": "../../test-recipe-schema.json",
  "testApplicationName": "next-app-app-dir",
  "buildCommand": "yarn install --pure-lockfile && npx playwright install && yarn build",
  "tests": [
    {
      "testName": "Playwright tests - Prod Mode",
      "testCommand": "yarn test:prod"
    },
    {
      "testName": "Playwright tests - Dev Mode",
      "testCommand": "yarn test:dev"
    }
  ],
  "canaryVersions": [
    {
      "dependencyOverrides": {
        "next": "latest",
        "react": "latest",
        "react-dom": "latest"
      }
    }
  ]
}
